### ISSUE TITLE
Where i got the vendor/autoload.php ?

### ISSUE THREAD

**Issue by tocan** [chickey/Epever-influxdb#1]
<?php
/*
 * PHP EpSolar Tracer Class (PhpEpsolarTracer) v0.9
 *
 */
 
//EPEver tracer php library
require_once 'PhpEpsolarTracer.php';
//influxDB php client library
require 'vendor/autoload.php';

-------------------------------------
 php logger.php
PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/epsolar/logger.php on line 10
PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/epsolar/logger.php on line 10

**Comment by chickey** [comment]
You need influxdb-php

curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
composer require influxdb/influxdb-php

sudo nano /etc/influxdb/influxdb.conf
Change enabled = false to enabled = true under the [admin] section.
